# dockerized virtual environment for ELK
version: '3'
services:

  elasticsearch:
    image: "elasticsearch:7.4.2"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./provision/global/etc/localtime:/etc/localtime
      - ./provision/global/etc/timezone:/etc/timezone
      - .state/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: "kibana:7.4.2"
    ports:
      - 15601:5601
    volumes:
      - ./provision/global/etc/localtime:/etc/localtime
      - ./provision/global/etc/timezone:/etc/timezone
      - ./provision/kibana/kibana.yml/:/usr/share/kibana/config/kibana.yml
